version: "3.8"
services:
  kotlin-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    command: tail -F anything
