name: ci

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Devcontainer
      run: bin/start_container.sh
    - name: Compile and run HelloWorld project in container
      run: | 
        bin/hop_in.sh
        kotlinc HelloWorld.kt -include-runtime -d HelloWorld.jar
        kotlin HelloWorld.jar